import '/imports/api/user/server/methods'
import '/imports/api/email/server/methods'
import '/imports/api/partners/server/methods'
import '/imports/api/notes/server/methods'
import './process_env_MAIL'
